---
- name: Git global settings
  git_config:
    scope: global
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ git_global_config }}"
