---
- name: Converge
  hosts: all
  vars:
    git_global_config:
      - name: pull.rebase
        value: "False"
      - name: user.email
        value: agl4@example.com
      - name: user.name
        value: Attila GOLONCSER
  roles:
    - agl4.git_config
