---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: update repos on debian
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Debian"
    - name: install git
      ansible.builtin.package:
        name: git
